import test from 'node:test';
import assert from 'node:assert/strict';
import { createDestructiveActionService } from '../src/services/destructive-actions.js';
const ctx={userId:'u1',workspaceId:'w1',role:'owner',source:'chatgpt'};
function harness(now=1000){const pending=new Map(),calls=[];const store={async putPending(row){pending.set(row.id,row)},async getPending(id){return pending.get(id)||null},async consumePending(id,at){const r=pending.get(id);pending.set(id,{...r,consumed_at:new Date(at).toISOString()})}};const repo={async previewDestructive(_ctx,action,targetId){calls.push(['preview',action,targetId]);return {targetId,connections:3,files:1}},async applyDestructive(_ctx,action,targetId){calls.push(['apply',action,targetId]);return {nodes:1,edges:3,files:0}}};return {svc:createDestructiveActionService({store,repo,now:()=>now,randomId:()=> 'confirm-1'}),pending,calls,store,repo};}
test('prepare returns preview and does not delete',async()=>{const h=harness();const p=await h.svc.prepareDestructiveAction(ctx,{action:'delete_node',targetId:'n1'});assert.equal(p.confirmationId,'confirm-1');assert.equal(p.preview.connections,3);assert.equal(h.calls.some(c=>c[0]==='apply'),false);});
test('valid confirmation applies once; repository owns atomic activity',async()=>{const h=harness();await h.svc.prepareDestructiveAction(ctx,{action:'delete_node',targetId:'n1'});const r=await h.svc.confirmDestructiveAction(ctx,'confirm-1');assert.equal(r.ok,true);assert.equal(h.calls.filter(c=>c[0]==='apply').length,1);await assert.rejects(()=>h.svc.confirmDestructiveAction(ctx,'confirm-1'),/já utilizada/);});
test('expired confirmation cannot apply',async()=>{const h=harness();await h.svc.prepareDestructiveAction(ctx,{action:'delete_node',targetId:'n1'});h.svc=createDestructiveActionService({store:h.store,repo:h.repo,now:()=>1000+11*60*1000,randomId:()=> 'x'});await assert.rejects(()=>h.svc.confirmDestructiveAction(ctx,'confirm-1'),/expirada/);assert.equal(h.calls.some(c=>c[0]==='apply'),false);});
test('confirmation is bound to actor and workspace',async()=>{const h=harness();await h.svc.prepareDestructiveAction(ctx,{action:'delete_node',targetId:'n1'});await assert.rejects(()=>h.svc.confirmDestructiveAction({...ctx,userId:'u2'},'confirm-1'),/não pertence/);await assert.rejects(()=>h.svc.confirmDestructiveAction({...ctx,workspaceId:'w2'},'confirm-1'),/não pertence/);});
