import test from 'node:test';
import assert from 'node:assert/strict';
import { createRuntime } from '../src/runtime.js';
import { projectPublicState } from '../src/github/state-store.js';
const b64=v=>Buffer.from(JSON.stringify(v)).toString('base64');
function fakeGitHub(initial){let state=structuredClone(initial),head='h1',tree='t1',seq=1;const blobs=new Map();return{async getRef(){return{object:{sha:head}}},async getCommit(){return{tree:{sha:tree}}},async getContent(path){const v=path==='data/public.json'?projectPublicState(state):state;return{content:b64(v),sha:'x'}},async commitAtomic({entries}){for(const e of entries){if(e.path==='data/state.json')state=JSON.parse(Buffer.from(e.contentBase64,'base64'));}head=`h${++seq}`;tree=`t${seq}`;return{sha:head,treeSha:tree}},async createBlob({content,encoding}){const sha=`b${blobs.size+1}`;blobs.set(sha,Buffer.from(content,encoding==='base64'?'base64':'utf8'));return{sha}},async getBlob(sha){return{encoding:'base64',content:blobs.get(sha).toString('base64')}}};}
const env={NEXUS_GITHUB_OWNER:'otavio',NEXUS_GITHUB_REPO:'NEXUS-DATA',NEXUS_GITHUB_TOKEN:'secret',NEXUS_WORKSPACE_ID:'w1',NEXUS_OWNER_USER_ID:'u1',NODE_ENV:'test'};
const seed={schemaVersion:1,workspace:{id:'w1',isPublic:true},profiles:[],members:[],nodes:[{id:'n1',workspaceId:'w1',name:'Persistente',type:'area',x:0,y:0,deletedAt:null}],edges:[],files:[],nodeFiles:[],activity:[],apiCredentials:[],browserSessions:[],adminSettings:{},pendingDestructiveActions:[]};
test('runtime uses github-backed adapters and no Supabase config',async()=>{const client=fakeGitHub(seed);const runtime=createRuntime({env,githubClient:client,publicRoot:new URL('../public/',import.meta.url)});const r=await runtime.app.handle({method:'GET',path:'/api/v2/public/graph',headers:{}});assert.equal(r.status,200);assert.equal(r.body.nodes[0].name,'Persistente');assert.equal(runtime.ownerContext.userId,'u1');assert.equal(runtime.config.githubRepo,'NEXUS-DATA');assert.ok(runtime.stateStore);assert.ok(runtime.storage);assert.ok(runtime.securityStore);});
test('new runtime instance sees writes from previous instance',async()=>{const client=fakeGitHub(seed);const a=createRuntime({env,githubClient:client,publicRoot:new URL('../public/',import.meta.url)});await a.repo.createNode(a.ownerContext,{name:'Depois do restart'});const b=createRuntime({env,githubClient:client,publicRoot:new URL('../public/',import.meta.url)});const g=await b.repo.getGraph(b.ownerContext);assert.ok(g.nodes.some(n=>n.name==='Depois do restart'));});
