import test from 'node:test';
import assert from 'node:assert/strict';
import { createGitHubNexusRepository } from '../src/repositories/github-nexus-repository.js';
import { projectPublicState } from '../src/github/state-store.js';
function memoryStateStore(initial={schemaVersion:1,workspace:{id:'w1',isPublic:true},profiles:[],members:[],nodes:[],edges:[],files:[],nodeFiles:[],activity:[],apiCredentials:[],browserSessions:[],adminSettings:{},pendingDestructiveActions:[]}){let state=structuredClone(initial),writes=0;return{get state(){return structuredClone(state)},get writes(){return writes},async readState(){return{state:structuredClone(state),headSha:`h${writes}`,baseTreeSha:`t${writes}`}},async readPublic(){return projectPublicState(state)},async mutate(fn){const draft=structuredClone(state);const out=await fn(draft)||{};for(const e of out.activityEvents||[])draft.activity.push({id:`a${draft.activity.length+1}`,createdAt:'2026-10-02T12:00:00Z',...e});state=draft;writes++;return{result:out.result,state:structuredClone(state),headSha:`h${writes}`}}};}
const owner={workspaceId:'w1',userId:'u1',role:'owner',source:'web'};
test('create and update node each use one state mutation with audit included',async()=>{const store=memoryStateStore();let n=0;const repo=createGitHubNexusRepository({stateStore:store,idFactory:()=>`id${++n}`,now:()=>Date.parse('2026-10-02T12:00:00Z')});const created=await repo.createNode(owner,{name:'Motor',type:'project',x:1,y:2});assert.equal(created.id,'id1');assert.equal(store.writes,1);assert.equal(store.state.activity.length,1);assert.equal(store.state.activity[0].action,'create');const updated=await repo.updateNode(owner,created.id,{note:'KNSU'});assert.equal(updated.note,'KNSU');assert.equal(store.writes,2);assert.equal(store.state.activity.length,2);assert.equal(store.state.activity[1].action,'update');});
test('graph and public projection enforce workspace and exclude deleted rows',async()=>{const store=memoryStateStore({schemaVersion:1,workspace:{id:'w1',isPublic:true},nodes:[{id:'n1',workspaceId:'w1',name:'A',x:0,y:0,deletedAt:null},{id:'n2',workspaceId:'w1',name:'B',x:0,y:0,deletedAt:'x'}],edges:[{id:'e1',workspaceId:'w1',source:'n1',target:'n1',deletedAt:null}],files:[],nodeFiles:[],activity:[]});const repo=createGitHubNexusRepository({stateStore:store});assert.deepEqual((await repo.getGraph(owner)).nodes.map(n=>n.id),['n1']);assert.deepEqual((await repo.getPublicGraph('w1')).nodes.map(n=>n.id),['n1']);await assert.rejects(()=>repo.getGraph({...owner,workspaceId:'other'}),/Workspace/);});
test('shared file survives unlink and node deletion from one node',async()=>{const store=memoryStateStore({schemaVersion:1,workspace:{id:'w1',isPublic:true},nodes:[{id:'n1',workspaceId:'w1',name:'A'},{id:'n2',workspaceId:'w1',name:'B'}],edges:[],files:[{id:'f1',workspaceId:'w1',name:'doc',storagePath:'files/f1/doc',deletedAt:null}],nodeFiles:[{nodeId:'n1',fileId:'f1'},{nodeId:'n2',fileId:'f1'}],activity:[]});const repo=createGitHubNexusRepository({stateStore:store});await repo.applyDestructive(owner,'delete_node','n1');assert.equal(store.state.files[0].deletedAt??null,null);assert.deepEqual(store.state.nodeFiles,[{nodeId:'n2',fileId:'f1'}]);});
test('legacy upserts are idempotent and preserve mapping',async()=>{const store=memoryStateStore();let i=0;const repo=createGitHubNexusRepository({stateStore:store,idFactory:()=>`g${++i}`});const a=await repo.upsertLegacyNode('w1','old',{name:'A'});const b=await repo.upsertLegacyNode('w1','old',{name:'A2'});assert.equal(a.id,b.id);assert.equal((await repo.getMigrationCounts('w1')).nodes,1);});
test('activity listing is bounded and newest first',async()=>{const activity=Array.from({length:120},(_,i)=>({id:`a${i}`,workspaceId:'w1',createdAt:new Date(1000+i).toISOString(),action:'x'}));const store=memoryStateStore({schemaVersion:1,workspace:{id:'w1',isPublic:true},nodes:[],edges:[],files:[],nodeFiles:[],activity});const repo=createGitHubNexusRepository({stateStore:store});const rows=await repo.listActivity(owner,500);assert.equal(rows.length,100);assert.equal(rows[0].id,'a119');});
